# Generated by Django 2.2.5 on 2019-10-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronjob',
            old_name='execution',
            new_name='executionTime',
        ),
    ]
